### ISSUE TITLE
Can't spoof "1 to many" for videos

### ISSUE THREAD

**Issue by glamouagency** [spoofzy/spoofzy#1]
When I try to spoof videos "1 to many" I get this alert: "Please select a mode using the main menu before uploading files." Even tho I selected the mode.

When I do the same thing with photos it works fine. So I expect it should work for videos too.

https://github.com/user-attachments/assets/a96ca1fb-3c87-46ea-8c02-fe6950897883

**Comment by spoofzy** [comment]
Hello,

Thanks for your detailed report. We have now fixed this issue, and confirmed it is working. 

Best,
Spoofzy Team
